SEED = 42   # For having reproducible experiments
WORKING_DIR = "./"
DATA_DIR = f"{WORKING_DIR}/data_folder"
OPTIMIZER = "Adam"
LR = 1e-3
LOSS = "MSELoss"
ONE_CYCLE_TOTAL_STEPS = 100
PATIENCE = 5
N_CHECKPOINTS = 3
MODEL_CLASS_MODULE = "models"
LOG_STEPS = 5
PINMEMORY = False
LOG_DIR = "logs"
DEVICES = 1